development:
  adapter: postgresql
  database: compramedb_dev
  encoding: utf8
  host: "/cloudsql/comprame-168801:us-central1:compramedb"
  password: VMware1
  pool: 5
  timeout: 5000
  username: gustavo


production:
  adapter: postgresql
  database: compramedb
  encoding: utf8
  host: "/cloudsql/comprame-168801:us-central1:compramedb"
  password: VMware1
  pool: 5
  timeout: 5000
  username: gustavo


test: 
  adapter: postgresql
  database: greatbuy_test
  encoding: unicode
  password: VMware1!
  pool: 5
  username: gustavo
