# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c27cb2762ef90c5062c7282f82e9138fd6b4511c9594d2911969f0655d40058d1bbd0dd1031e0383478d7dc984040395108d9a8b90a91c969b8470aac086c915

test:
  secret_key_base: 13999bb6aa49847810b7bfaf871dc4b795a0e5c90749caf2c5c6bbeb5e973146cd83e02e44762cb678d291c9e7b97fe17b95e58ddf34390d1c2e5e1f79524862

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 14bb45d0d6c899eaf666455d408c27fdcfd7c0e0ae24d828c76ea9cdd884586e7a8b2b3e2740959835a722917ef3198d2cfca6947fce2b341f7f1156760d5545
